version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/recommendation-engine/java"
    schedule:
      interval: weekly
      day: "sunday"
    open-pull-requests-limit: 20

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
      day: "sunday"
    open-pull-requests-limit: 10
    groups:
      github-actions:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "docker-compose"
    directory: "/recommendation-engine"
    schedule:
      interval: weekly
      day: "sunday"
    open-pull-requests-limit: 10

