-- Vertex type for text chunks with vector embeddings
CREATE VERTEX TYPE Chunk IF NOT EXISTS;
CREATE PROPERTY Chunk.content IF NOT EXISTS STRING;
CREATE PROPERTY Chunk.source IF NOT EXISTS STRING;
CREATE PROPERTY Chunk.chunkIndex IF NOT EXISTS INTEGER;
CREATE PROPERTY Chunk.embedding IF NOT EXISTS LIST;

-- Entity vertex types (knowledge graph nodes)
CREATE VERTEX TYPE Entity IF NOT EXISTS;
CREATE PROPERTY Entity.name IF NOT EXISTS STRING;
CREATE VERTEX TYPE Person IF NOT EXISTS EXTENDS Entity;
CREATE VERTEX TYPE Concept IF NOT EXISTS EXTENDS Entity;
CREATE VERTEX TYPE Organization IF NOT EXISTS EXTENDS Entity;

-- Edge types
CREATE EDGE TYPE MENTIONS IF NOT EXISTS;
CREATE EDGE TYPE RELATES_TO IF NOT EXISTS;
CREATE EDGE TYPE WORKS_AT IF NOT EXISTS;
CREATE EDGE TYPE AUTHORED IF NOT EXISTS;

-- Vector index for chunk embeddings (4 dimensions for sample data)
CREATE INDEX IF NOT EXISTS ON Chunk (embedding) LSM_VECTOR METADATA { dimensions: 4, similarity: 'COSINE' };
