CREATE TIMESERIES TYPE SensorReading TIMESTAMP ts TAGS (sensor_id STRING, location STRING) FIELDS (temperature DOUBLE, humidity DOUBLE, pressure DOUBLE) SHARDS 16 RETENTION 90 DAYS
CREATE TIMESERIES TYPE ServiceMetrics TIMESTAMP ts TAGS (service_id STRING, server_id STRING) FIELDS (request_count LONG, error_count LONG, latency_ms DOUBLE) SHARDS 8 RETENTION 30 DAYS
CREATE VERTEX TYPE Building IF NOT EXISTS
CREATE PROPERTY Building.name IF NOT EXISTS STRING
CREATE VERTEX TYPE Floor IF NOT EXISTS
CREATE PROPERTY Floor.name IF NOT EXISTS STRING
CREATE PROPERTY Floor.level IF NOT EXISTS INTEGER
CREATE VERTEX TYPE Sensor IF NOT EXISTS
CREATE PROPERTY Sensor.name IF NOT EXISTS STRING
CREATE PROPERTY Sensor.sensor_id IF NOT EXISTS STRING
CREATE INDEX IF NOT EXISTS ON Sensor (sensor_id) UNIQUE
CREATE VERTEX TYPE Server IF NOT EXISTS
CREATE PROPERTY Server.name IF NOT EXISTS STRING
CREATE PROPERTY Server.server_id IF NOT EXISTS STRING
CREATE INDEX IF NOT EXISTS ON Server (server_id) UNIQUE
CREATE VERTEX TYPE Service IF NOT EXISTS
CREATE PROPERTY Service.name IF NOT EXISTS STRING
CREATE PROPERTY Service.service_id IF NOT EXISTS STRING
CREATE INDEX IF NOT EXISTS ON Service (service_id) UNIQUE
CREATE EDGE TYPE HAS_FLOOR IF NOT EXISTS
CREATE EDGE TYPE INSTALLED_IN IF NOT EXISTS
CREATE EDGE TYPE RUNS_ON IF NOT EXISTS
CREATE EDGE TYPE DEPENDS_ON IF NOT EXISTS
