-- Fraud domain
CREATE VERTEX TYPE Account IF NOT EXISTS;
CREATE PROPERTY Account.accountId IF NOT EXISTS STRING;
CREATE PROPERTY Account.accountType IF NOT EXISTS STRING;
CREATE PROPERTY Account.signupSource IF NOT EXISTS STRING;
CREATE PROPERTY Account.flagged IF NOT EXISTS BOOLEAN;
CREATE PROPERTY Account.behaviorVec IF NOT EXISTS LIST;
CREATE INDEX IF NOT EXISTS ON Account (accountId) UNIQUE;
CREATE VERTEX TYPE Merchant IF NOT EXISTS;
CREATE PROPERTY Merchant.merchantId IF NOT EXISTS STRING;
CREATE PROPERTY Merchant.category IF NOT EXISTS STRING;
CREATE PROPERTY Merchant.riskTier IF NOT EXISTS STRING;
-- Recommendation domain
CREATE VERTEX TYPE User IF NOT EXISTS;
CREATE PROPERTY User.userId IF NOT EXISTS STRING;
CREATE PROPERTY User.preferenceVec IF NOT EXISTS LIST;
CREATE INDEX IF NOT EXISTS ON User (userId) UNIQUE;
CREATE VERTEX TYPE Product IF NOT EXISTS;
CREATE PROPERTY Product.productId IF NOT EXISTS STRING;
CREATE PROPERTY Product.name IF NOT EXISTS STRING;
CREATE PROPERTY Product.category IF NOT EXISTS STRING;
CREATE PROPERTY Product.price IF NOT EXISTS FLOAT;
CREATE PROPERTY Product.embedding IF NOT EXISTS LIST;
-- Maintenance domain
CREATE VERTEX TYPE Equipment IF NOT EXISTS;
CREATE PROPERTY Equipment.equipmentId IF NOT EXISTS STRING;
CREATE PROPERTY Equipment.name IF NOT EXISTS STRING;
CREATE PROPERTY Equipment.specifications IF NOT EXISTS STRING;
CREATE PROPERTY Equipment.failureRate IF NOT EXISTS FLOAT;
CREATE INDEX IF NOT EXISTS ON Equipment (equipmentId) UNIQUE;
CREATE VERTEX TYPE Sensor IF NOT EXISTS;
CREATE PROPERTY Sensor.sensorId IF NOT EXISTS STRING;
CREATE PROPERTY Sensor.sensorType IF NOT EXISTS STRING;
CREATE PROPERTY Sensor.unit IF NOT EXISTS STRING;
-- Edge types
CREATE EDGE TYPE TRANSFERRED IF NOT EXISTS;
CREATE PROPERTY TRANSFERRED.amount IF NOT EXISTS FLOAT;
CREATE PROPERTY TRANSFERRED.recordedAt IF NOT EXISTS DATETIME;
CREATE EDGE TYPE LINKED_DEVICE IF NOT EXISTS;
CREATE PROPERTY LINKED_DEVICE.deviceId IF NOT EXISTS STRING;
CREATE EDGE TYPE TRANSACTED IF NOT EXISTS;
CREATE PROPERTY TRANSACTED.amount IF NOT EXISTS FLOAT;
CREATE PROPERTY TRANSACTED.recordedAt IF NOT EXISTS DATETIME;
CREATE EDGE TYPE PURCHASED IF NOT EXISTS;
CREATE EDGE TYPE DEPENDS_ON IF NOT EXISTS;
CREATE PROPERTY DEPENDS_ON.criticality IF NOT EXISTS STRING;
CREATE EDGE TYPE MONITORED_BY IF NOT EXISTS;
-- Document types
CREATE DOCUMENT TYPE TransactionMetric IF NOT EXISTS;
CREATE PROPERTY TransactionMetric.accountId IF NOT EXISTS STRING;
CREATE PROPERTY TransactionMetric.txCount IF NOT EXISTS LONG;
CREATE PROPERTY TransactionMetric.totalAmount IF NOT EXISTS FLOAT;
CREATE PROPERTY TransactionMetric.recordedAt IF NOT EXISTS DATETIME;
CREATE DOCUMENT TYPE SensorReading IF NOT EXISTS;
CREATE PROPERTY SensorReading.equipmentId IF NOT EXISTS STRING;
CREATE PROPERTY SensorReading.temperature IF NOT EXISTS FLOAT;
CREATE PROPERTY SensorReading.vibration IF NOT EXISTS FLOAT;
CREATE PROPERTY SensorReading.pressure IF NOT EXISTS FLOAT;
CREATE PROPERTY SensorReading.recordedAt IF NOT EXISTS DATETIME;
CREATE DOCUMENT TYPE FeatureSnapshot IF NOT EXISTS;
CREATE PROPERTY FeatureSnapshot.entityId IF NOT EXISTS STRING;
CREATE PROPERTY FeatureSnapshot.entityType IF NOT EXISTS STRING;
CREATE PROPERTY FeatureSnapshot.featureVector IF NOT EXISTS LIST;
CREATE PROPERTY FeatureSnapshot.computedAt IF NOT EXISTS DATETIME;
CREATE PROPERTY FeatureSnapshot.modelVersion IF NOT EXISTS STRING;
-- Vector indexes
CREATE INDEX IF NOT EXISTS ON Account (behaviorVec) LSM_VECTOR METADATA { dimensions: 4, similarity: 'COSINE' };
CREATE INDEX IF NOT EXISTS ON Product (embedding) LSM_VECTOR METADATA { dimensions: 4, similarity: 'COSINE' };
