-- Vertex types
CREATE VERTEX TYPE Identity IF NOT EXISTS
CREATE PROPERTY Identity.email IF NOT EXISTS STRING
CREATE PROPERTY Identity.identityType IF NOT EXISTS STRING
CREATE PROPERTY Identity.department IF NOT EXISTS STRING
CREATE PROPERTY Identity.title IF NOT EXISTS STRING
CREATE PROPERTY Identity.access_pattern_vec IF NOT EXISTS LIST
CREATE INDEX IF NOT EXISTS ON Identity (email) UNIQUE
CREATE VERTEX TYPE `Group` IF NOT EXISTS
CREATE PROPERTY `Group`.name IF NOT EXISTS STRING
CREATE PROPERTY `Group`.description IF NOT EXISTS STRING
CREATE INDEX IF NOT EXISTS ON `Group` (name) UNIQUE
CREATE VERTEX TYPE Role IF NOT EXISTS
CREATE PROPERTY Role.name IF NOT EXISTS STRING
CREATE PROPERTY Role.description IF NOT EXISTS STRING
CREATE INDEX IF NOT EXISTS ON Role (name) UNIQUE
CREATE VERTEX TYPE Permission IF NOT EXISTS
CREATE PROPERTY Permission.action IF NOT EXISTS STRING
CREATE VERTEX TYPE Resource IF NOT EXISTS
CREATE PROPERTY Resource.name IF NOT EXISTS STRING
CREATE PROPERTY Resource.classification IF NOT EXISTS STRING
CREATE PROPERTY Resource.data_sensitivity IF NOT EXISTS STRING
CREATE PROPERTY Resource.compliance_scope IF NOT EXISTS STRING
CREATE INDEX IF NOT EXISTS ON Resource (name) UNIQUE
CREATE VERTEX TYPE Policy IF NOT EXISTS
CREATE PROPERTY Policy.name IF NOT EXISTS STRING
CREATE PROPERTY Policy.policyType IF NOT EXISTS STRING
CREATE PROPERTY Policy.description IF NOT EXISTS STRING
CREATE INDEX IF NOT EXISTS ON Policy (name) UNIQUE
-- Edge types
CREATE EDGE TYPE MEMBER_OF IF NOT EXISTS
CREATE EDGE TYPE HAS_ROLE IF NOT EXISTS
CREATE EDGE TYPE GRANTS IF NOT EXISTS
CREATE EDGE TYPE APPLIES_TO IF NOT EXISTS
CREATE EDGE TYPE INHERITS_FROM IF NOT EXISTS
CREATE EDGE TYPE GOVERNED_BY IF NOT EXISTS
-- Document type for time-series access logs
CREATE DOCUMENT TYPE AccessLog IF NOT EXISTS
CREATE PROPERTY AccessLog.identityEmail IF NOT EXISTS STRING
CREATE PROPERTY AccessLog.resourceName IF NOT EXISTS STRING
CREATE PROPERTY AccessLog.action IF NOT EXISTS STRING
CREATE PROPERTY AccessLog.source_ip IF NOT EXISTS STRING
CREATE PROPERTY AccessLog.recordedAt IF NOT EXISTS DATETIME
-- Vector index for behavioral anomaly detection
CREATE INDEX IF NOT EXISTS ON Identity (access_pattern_vec) LSM_VECTOR METADATA { dimensions: 8, similarity: 'COSINE' }
